runtime: nodejs20
instance_class: F1
env: standard


env_variables:
  RAZORPAY_KEY_ID: "rzp_test_kC99JKxEFoZUns"
  RAZORPAY_KEY_SECRET: "bDfo3ZL782eHZOY2raOVIOkE"
  DATABASE_URI: "mongodb+srv://mongotut:mongo124@cluster0.k7ehn.mongodb.net/RAJOR_PAY?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET : "sivabalaji@2004"